### ISSUE TITLE
Interface implementations missing from schema with graphql-js 0.5.0

### ISSUE THREAD

**Issue by jimkyndemeyer** [matthewmueller/graph.ql#22]
Hey.

First of all, thanks for this awesome library.

There's a breaking change in [graphql-js v.0.5.0](https://github.com/graphql/graphql-js/releases/tag/v0.5.0) that reads as follows:
- Types which implement an interface but are otherwise not referenced as a field return type are no longer automatically added to the Schema

It appears that it's now possible to pass types to include explicitly in the constructor of `graphql.GraphQLSchema` in [index.js](https://github.com/matthewmueller/graph.ql/blob/master/lib/index.js#L27):

``` JavaScript
function Create (schema, implementation) {

  // ....

  // create an array of all types
  var all_types = Object.keys(object_types).map(function(typeName) {
    return object_types[typeName];
  });

  var schema = new graphql.GraphQLSchema({
    query: object_types['Query'],
    mutation: object_types['Mutation'],
    subscription: object_types['Subscription'],
    // and pass them here to include them in v.0.5.0 of graphql-js
    types: all_types
  });

  // .....
}
```

Adding all_types to the schema fixed our use case. I'm not sure whether this should be the default behaviour though.

**Comment by ianstormtaylor** [comment]
+1 running into this as well!

Edit: nvm no I wasn't, although still seems valid.

**Comment by Aleph-Z** [comment]
+1

**Comment by migueloller** [comment]
Here's an alternative: https://github.com/bloveit/graphql-utilities

**Comment by aruprakshit** [comment]
I have this

```
const Schema = require("graph.ql");

const DATA = [
  { username: "catherine" },
  { director: "catherine hardwicke" },
  { author: "catherine cookson", isbn: "IO19939" }
];

const schema = Schema(
  `
  interface SearchableType {
    searchPreviewText: String
  }

  type User implements SearchableType {
    username: String
    searchPreviewText: String
  }

  type Movie implements SearchableType {
    director: String
    searchPreviewText: String
  }

  type Book implements SearchableType {
    author: String
    isbn: String
    searchPreviewText: String
  }

  type Query {
    search(text: String!): [SearchableType]
  }
`,
  {
    Query: {
      search(query, args) {
        const text = args.text;

        return DATA.filter(d => {
          const searchableProperty = d.username || d.director || d.author;
          return searchableProperty.includes(text);
        });
      }
    },
    SearchableType: {
      resolveType(data) {
        if (data.username) {
          return "User";
        }

        if (data.director) {
          return "Movie";
        }

        if (data.author) {
          return "Book";
        }
      }
    },
    User: {
      isTypeOf(data) {
        return !!data.username;
      },
      searchPreviewText(data) {
        return `(user) ${data.username}`;
      }
    },
    Movie: {
      isTypeOf(data) {
        return !!data.director;
      },
      searchPreviewText(data) {
        return `(movie) ${data.director}`;
      }
    },
    Book: {
      isTypeOf(data) {
        return !!data.author;
      },
      searchPreviewText(data) {
        return `(user) ${data.author}`;
      }
    }
  }
);

schema(`
  {
    search(text: "co") {
      searchPreviewText
      ... on User {
        username
      }
      ... on Movie {
        director
      }
      ... on Book {
        author
        isbn
      }
    }
  }
`).then(res => console.dir(res, { depth: null, colors: true }));

module.exports = schema;
```

When I run it, I get error as:

```
~$ cd GraphQL/learning-gql/graphql-tour-interfaces-and-unions/
graphql-tour-interfaces-and-unions (master)$ node interface_schema.js
{ errors:
   [ { GraphQLError: Unknown type "User".
    at Object.NamedType (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/validation/rules/KnownTypeNames.js:66:29)
    at Object.enter (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/language/visitor.js:296:29)
    at Object.enter (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/language/visitor.js:338:25)
    at visit (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/language/visitor.js:228:26)
    at visitUsingRules (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/validation/validate.js:75:22)
    at validate (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/validation/validate.js:60:10)
    at Promise.then.errors (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/graphql.js:54:51)
    at new Promise (<anonymous>)
    at Object.graphql (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/graphql.js:51:10)
    at query (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graph.ql/lib/index.js:34:20)
       message: 'Unknown type "User".',
       locations: [ { line: 5, column: 14 } ],
       path: undefined },
     { GraphQLError: Unknown type "Movie".
    at Object.NamedType (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/validation/rules/KnownTypeNames.js:66:29)
    at Object.enter (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/language/visitor.js:296:29)
    at Object.enter (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/language/visitor.js:338:25)
    at visit (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/language/visitor.js:228:26)
    at visitUsingRules (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/validation/validate.js:75:22)
    at validate (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/validation/validate.js:60:10)
    at Promise.then.errors (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/graphql.js:54:51)
    at new Promise (<anonymous>)
    at Object.graphql (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/graphql.js:51:10)
    at query (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graph.ql/lib/index.js:34:20)
       message: 'Unknown type "Movie".',
       locations: [ { line: 8, column: 14 } ],
       path: undefined },
     { GraphQLError: Unknown type "Book".
    at Object.NamedType (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/validation/rules/KnownTypeNames.js:66:29)
    at Object.enter (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/language/visitor.js:296:29)
    at Object.enter (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/language/visitor.js:338:25)
    at visit (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/language/visitor.js:228:26)
    at visitUsingRules (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/validation/validate.js:75:22)
    at validate (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/validation/validate.js:60:10)
    at Promise.then.errors (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/graphql.js:54:51)
    at new Promise (<anonymous>)
    at Object.graphql (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graphql/graphql.js:51:10)
    at query (/Users/aruprakshit/GraphQL/learning-gql/graphql-tour-interfaces-and-unions/node_modules/graph.ql/lib/index.js:34:20)
       message: 'Unknown type "Book".',
       locations: [ { line: 11, column: 14 } ],
       path: undefined } ] }
```

Why the mentioned PR is not getting merged?
