### ISSUE TITLE
Relay support

### ISSUE THREAD

**Issue by zuhair-naqvi** [matthewmueller/graph.ql#3]
When I try to implement Relay semantics, i.e. Nodes, edges, connections etc. the library is throwing the following exception:

```
[ 'Error: Expected "{" but got ":"',
     '',
     '    ',
     '        type User : Node {',
     '                 ^',
     '          id: ID!',

     '',
     '    at Parse.error (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/parse.js:545:10)',
     '    at Parse.required (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/parse.js:68:16)',
     '    at Parse.expect (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/parse.js:77:8)',
     '    at Parse.object_type_definition (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/parse.js:187:10)',
     '    at Parse.type_definition (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/parse.js:167:15)',
     '    at Parse.list (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/parse.js:140:44)',
     '    at Parse.document (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/parse.js:119:26)',
     '    at new Parse (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/parse.js:33:15)',
     '    at Parse (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/parse.js:28:40)',
     '    at Create (/Users/zuhairnaqvi/dev/project/project-graphql/node_modules/graph.ql/lib/index.js:26:20)' ] }
```

I thought this library was 100% compliant with GraphQL spec but looks like it doesn't support interfaces. Any ideas how to get around this?

I really like the simplicity of schema definition graph.ql provides but I also need to use Relay!

**Comment by codecvlt** [comment]
I'm also wondering how this library would work with relay. I'm using graphql-js and it's definitely on the heavy side.
